spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://192.168.198.129:3306/demo?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    url: jdbc:p6spy:mysql://192.168.198.130:3306/sell?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#  jackson:
#    default-property-inclusion: non_null
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-enums-package: com.imooc.sell.enums
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx6ad144e54af67d87
  mpAppSecret: 9b848bb6a4fab51e36136db9110b0823